# Generated by Django 4.0 on 2021-12-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.CharField(max_length=1000, verbose_name='Ссылка на изображение')),
                ('release_date', models.CharField(max_length=30, verbose_name='Дата релиза')),
                ('lte_exists', models.BooleanField(verbose_name='Наличие LTE')),
            ],
        ),
    ]
